// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_GSULBLyJOufAe-8uVi_NYe4Dj_O7zr0',
    appId: '1:542204481812:web:2cf1f23f71f2c73b2a7201',
    messagingSenderId: '542204481812',
    projectId: 'my-flutter-projectcli',
    authDomain: 'my-flutter-projectcli.firebaseapp.com',
    storageBucket: 'my-flutter-projectcli.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2D4ypLi_RTdEVs7XKBksFEVfKzm-TfeY',
    appId: '1:542204481812:android:6acd2bf3bc2c2bc82a7201',
    messagingSenderId: '542204481812',
    projectId: 'my-flutter-projectcli',
    storageBucket: 'my-flutter-projectcli.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNO3D8SHv8QSyQzy6eMNbAGP7lhwCr1uI',
    appId: '1:542204481812:ios:06e439c6d19d49b62a7201',
    messagingSenderId: '542204481812',
    projectId: 'my-flutter-projectcli',
    storageBucket: 'my-flutter-projectcli.appspot.com',
    iosBundleId: 'com.example.flutterproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNO3D8SHv8QSyQzy6eMNbAGP7lhwCr1uI',
    appId: '1:542204481812:ios:e8c7b651521f4dcd2a7201',
    messagingSenderId: '542204481812',
    projectId: 'my-flutter-projectcli',
    storageBucket: 'my-flutter-projectcli.appspot.com',
    iosBundleId: 'com.example.flutterproject.RunnerTests',
  );
}
